name: CI

on:
  push:
    branches: [main, master, 43-add-github-actions]
  pull_request:
    branches: [main, master, 43-add-github-actions]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests with tox
        run: tox -e py312,test,lint
