name: Build documentation

on:
  push:
    branches: [main, master, 43-add-github-actions]
  pull_request:
    branches: [main, master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]

      - name: Build docs
        run: |
          cd docs
          make html
